In [58]:
import numpy as np

In [59]:
#Task 1
vector_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=float)
vector_1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
#Task 2
matrix_1 = np.zeros((3, 3))
matrix_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
#Task 3
matrix_2 = np.random.randint(1, 11, size=(5, 5))
matrix_2

array([[ 2,  6,  9, 10,  3],
       [ 6,  6,  6,  5,  7],
       [ 8, 10,  1,  5,  7],
       [ 6,  6,  5,  3, 10],
       [ 4,  3, 10,  5,  9]])

In [62]:
#Task 4
matrix_3 = np.random.random((4, 4))
matrix_3

array([[0.09363125, 0.63772822, 0.56669881, 0.48697826],
       [0.42089554, 0.41445843, 0.31493771, 0.44350417],
       [0.06254495, 0.72198224, 0.52814101, 0.58294474],
       [0.12971487, 0.02688776, 0.26899782, 0.59126976]])

In [63]:
#Task 5
vector_2 = np.random.randint(1, 11, 5)
vector_3 = np.random.randint(1, 11, 5)
vector_2 + vector_3
vector_2 - vector_3
vector_2 * vector_3

array([63, 20,  9, 80, 18])

In [64]:
#Task 6
vector_4 = np.random.randint(1, 11, 7)
vector_5 = np.random.randint(1, 11, 7)
np.dot(vector_4, vector_5)

410

In [65]:
#Task 7
matrix_4 = np.random.randint(1, 11, size=(2, 2))
matrix_5 = np.random.randint(1, 11, size=(2, 3))
np.dot(matrix_4, matrix_5)

array([[ 79, 149,  86],
       [ 42,  91,  45]])

In [66]:
#Task 8
matrix_6 = np.random.randint(1, 11, size=(3, 3))
np.linalg.inv(matrix_6)

array([[ 0.58823529, -0.23529412, -0.29411765],
       [ 0.15966387,  0.05042017, -0.1512605 ],
       [-0.55462185,  0.19327731,  0.42016807]])

In [67]:
#Task 9
matrix_7 = np.random.random((4 ,4))
matrix_7.T

array([[0.55537433, 0.70602626, 0.9716595 , 0.52662347],
       [0.84325311, 0.70511464, 0.4203859 , 0.56181591],
       [0.23122667, 0.75485705, 0.39094111, 0.88014114],
       [0.36255538, 0.68393041, 0.91953275, 0.38137087]])

In [68]:
#Task 10
matrix_8 = np.random.randint(1, 11, (3, 4))
vector_6 = np.random.randint(1, 11, 4)
np.dot(matrix_8, vector_6)

array([124, 110, 114])

In [69]:
#Task 11
matrix_9 = np.random.random((2, 3))
vector_7 = np.random.random(3)
np.dot(matrix_9, vector_7)

array([1.16468676, 0.99348839])

In [70]:
#Task 12
matrix_10 = np.random.randint(1, 11, size=(2, 2))
matrix_11 = np.random.randint(1, 11, size=(2, 2))
np.multiply(matrix_10, matrix_11)

array([[20, 50],
       [12, 60]])

In [71]:
#Task 13
matrix_12 = np.random.randint(1, 11, size=(2, 2))
matrix_13 = np.random.randint(1, 11, size=(2, 2))
np.matmul(matrix_12, matrix_13)

array([[117,  42],
       [ 34,  12]])

In [72]:
#Task 14
matrix_14 = np.random.randint(1, 101, size=(5, 5))
np.sum(matrix_14)

1214

In [73]:
#Task 15
matrix_15 = np.random.randint(1, 11, size=(4, 4))
matrix_16 = np.random.randint(1, 11, size=(4, 4))
np.subtract(matrix_15, matrix_16)

array([[ 7,  4,  1, -8],
       [-1, -1, -5, -5],
       [-6,  3,  1,  1],
       [ 1,  6,  1,  7]])

In [74]:
#Task 16
matrix_17 = np.random.random((3, 3))
np.sum(matrix_17, axis=1)

array([1.50545101, 0.96045321, 1.36807345])

In [75]:
#Task 17
matrix_18 = np.random.randint(-10, 10, size=(3, 4))
np.square(matrix_18)

array([[ 36, 100,   4,   4],
       [ 81,  36,  49, 100],
       [  1,  64, 100,  81]])

In [76]:
#Task 18
vector_8 = np.random.randint(1, 51, size=4)
np.sqrt(vector_8)

array([4.12310563, 6.32455532, 7.07106781, 6.92820323])